linters-settings:
  lll:
    line-length: 120
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/cloudnative-pg/plugin-barman-cloud)
      - blank
      - dot
  nlreturn:
    # Size of the block (including return statement that is still "OK")
    # so no return split required.
    # Default: 1
    block-size: 3

issues:
  exclude-rules:
    # Allow dot imports for ginkgo and gomega
    - source: ginkgo|gomega
      linters:
        - revive
      text: "should not use dot imports"
    - linters:
        - stylecheck
      text: "should not use dot imports"
  exclude-dirs:
    - vendor

linters:
  enable-all: true
  disable:
    - depguard
    - err113
    - exhaustruct
    - execinquery
    - exportloopref
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - godox
    - gomnd
    - paralleltest
    - testpackage
    - varnamelen
    - wsl

run:
  timeout: 10m
  allow-parallel-runners: true
