apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-server
spec:
  secretName: minio-server-tls
  commonName: minio
  dnsNames:
    - minio

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: false
  usages:
    - server auth

  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
