apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: minio-store
spec:
  retentionPolicy: "1m"
  instanceSidecarConfiguration:
    logLevel: "debug"
    retentionPolicyIntervalSeconds: 1800
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    additionalContainerArgs:
    - --log-level=debug
    startupProbe:
      initialDelaySeconds: 1
      timeoutSeconds: 10
      periodSeconds: 1
      failureThreshold: 10
      successThreshold: 1
    livenessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 5
      periodSeconds: 10
      failureThreshold: 3
      successThreshold: 1
    readinessProbe:
      initialDelaySeconds: 5
      timeoutSeconds: 5
      periodSeconds: 5
      failureThreshold: 3
      successThreshold: 1
  configuration:
    endpointCA:
      name: minio-server-tls
      key: tls.crt
    destinationPath: s3://backups/
    endpointURL: https://minio:9000
    s3Credentials:
      accessKeyId:
        name: minio
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: minio
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
      maxParallel: 8
    data:
      additionalCommandArgs:
        - "--min-chunk-size=5MB"
        - "--read-timeout=60"
        - "-vv"
