apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mc
  name: mc
spec:
  containers:
  - env:
    - name: MC_HOST_minio
      value: http://chooJeiroroo2noquomei2uuceisheth:ongeiqueitohL0queeLohkiur2quaing@minio:9000
    image: minio/mc
    name: mc
    resources: {}
    # Keep the pod up to exec stuff on it
    command:
      - sleep
      - "3600"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
