apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg-system
resources:
- certificate-issuer.yaml
- client-certificate.yaml
- deployment.yaml
- server-certificate.yaml
- service.yaml
- ../config/crd
- ../config/rbac
images:
- name: plugin-barman-cloud
  newName: ghcr.io/cloudnative-pg/plugin-barman-cloud-testing
  newTag: main
secretGenerator:
- literals:
  - SIDECAR_IMAGE=ghcr.io/cloudnative-pg/plugin-barman-cloud-sidecar-testing:main
  name: plugin-barman-cloud
