apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: barman-cloud-server
spec:
  secretName: barman-cloud-server-tls
  commonName: barman-cloud
  dnsNames:
    - barman-cloud

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: false
  usages:
    - server auth

  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
