apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: object-store-server
spec:
  secretName: object-store-tls
  commonName: object-store
  dnsNames:
    - object-store
    - object-store.default
    - object-store.default.svc

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: false
  usages:
    - server auth

  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
