name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # We need the full history for the commitlint task
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Install Dagger
        env:
          # renovate: datasource=github-tags depName=dagger/dagger versioning=semver
          DAGGER_VERSION: 0.13.3
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | BIN_DIR=$HOME/.local/bin sh
      - name: Run CI task
        run: |
          task ci
      - name: Write manifest
        run: |
          task manifest
      - name: Publish images
        if: |
          github.event_name == 'workflow_dispatch' ||
          github.event.pull_request.head.repo.full_name == github.repository
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          task publish
      - name: Attach manifest to workflow run
        uses: actions/upload-artifact@v4
        with:
          name: manifest.yaml
          path: ./manifest.yaml
